FROM openjdk:11-jdk-slim

ARG BACKUP_FTP_HOST
ARG BACKUP_FTP_PORT
ARG BACKUP_FTP_USERNAME
ARG BACKUP_FTP_PASSWORD
ARG BACKUP_FTP_LOCAL_FILE
ARG BACKUP_FTP_REMOTE_FILE

ENV BACKUP_FTP_HOST=$BACKUP_FTP_HOST
ENV BACKUP_FTP_PORT=$BACKUP_FTP_PORT
ENV BACKUP_FTP_USERNAME=$BACKUP_FTP_USERNAME
ENV BACKUP_FTP_PASSWORD=$BACKUP_FTP_PASSWORD
ENV BACKUP_FTP_LOCAL_FILE=$BACKUP_FTP_LOCAL_FILE
ENV BACKUP_FTP_REMOTE_FILE=$BACKUP_FTP_REMOTE_FILE

COPY . .
RUN chmod +x gradlew
RUN apt update && apt-get install python3 -y
RUN python3 ./docker/db_backupper.py

RUN ./gradlew clean build
ENTRYPOINT java -jar "build/libs/api-0.0.1-SNAPSHOT.jar"

EXPOSE 8080
